on: [push, pull_request]
name: lint
jobs:
  fmt:
    name: cargo fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: cargo fmt
        run: cargo fmt --all -- --check

  clippy:
    name: cargo clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: cargo clippy
        run: cargo clippy --workspace --all-features --tests -- -D warnings

  release:
    name: cargo release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo +stable install cargo-release
      - run: cargo release --workspace patch

  readme:
    name: cargo readme
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo +stable install cargo-readme
      - run: cd doxed-derive && cargo readme > README.md
      - run: cd doxed && cargo readme > README.md
      - run: git diff --exit-code